import Headd from 'next/head'



export default function Head(){

    return (

        <Headd>
        <title>Adrian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Headd>
    )


}