import Head from 'next/head'
import {
  AiFillTwitterCircle,
  AiFillMail,
  AiFillLinkedin,
  AiFillGithub
} from "react-icons/ai";


import { motion } from "framer-motion"

import deved from "../public/dev-ed-wave.png";

import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";

// Components
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Presentation from '@/components/Presentation';



import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
// logos
import javascriptlogo from "../public/javascript-svgrepo-com.svg";
import reactlogo from "../public/reactlogo.svg"
import javalogo from "../public/java.svg"
import htmllogo from "../public/htmllogo.svg"
import nodejslogo from "../public/nodejs.svg"
import mongodblogo from "../public/mongodblogo.svg"
import mysqllogo from "../public/mysqllogo.svg"
import csslogo from "../public/csslogo.svg"

import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className="dark">
      <Head>
        <title>Adrian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <Header></Header>
          <Presentation></Presentation>
         
          
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">About my skills</h3>
            
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
          
              <h1 className="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl"><span className="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">Front-end stack</span></h1>


              <Image src={javascriptlogo} width={100} height={100} alt="design" />
              <Image src={reactlogo} width={100} height={100} alt="design" />
              <Image src={htmllogo} width={100} height={100} alt="design" />
              <Image src={csslogo} width={100} height={100} alt="design" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              
              <h1 className="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl"><span className="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">Back-end stack</span></h1>
              <Image src={javalogo} width={100} height={100} alt="example"/>
              <Image src={nodejslogo} width={100} height={100} alt="example"/>
            </div>


            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            
              <h1 className="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl"><span className="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">Database stack</span></h1>
              <Image src={mongodblogo} width={100} height={100} alt="example"/>
              <Image src={mysqllogo} width={100} height={100} alt="example"/>
             
            </div>
            
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since 
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and c
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a href="https://socialapp-ruddy.vercel.app/">
              <Image
                className="rounded-lg object-cover"
                alt=''
                layout="responsive"
                src={web1}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover hover:hover08"
                alt=''
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover hover:"
                alt=''
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                alt=''
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                alt=''
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                alt=''
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    
    </div>
  );
}